from __future__ import annotations

import argparse
import asyncio
from pathlib import Path
from typing import Any

import httpx
from pydantic import BaseModel, Field

from backend.cases.schemas import PreparedCase, VitalSigns
from backend.cases.trajectory_review import TrajectoryScenario, build_trajectory_review_packet
from backend.llm.client import LLMClient, LLMConfig
from backend.personas.service import answer_persona
from backend.state.context import consult_context, nurse_context, patient_context
from backend.state.engine import start_case


class PersonaGuardProbe(BaseModel):
    role: str
    state_vitals: VitalSigns
    model_claim: str
    guarded_text: str
    stable_claim_removed: bool
    wrong_vitals_removed: bool
    state_anchor_present: bool
    passed: bool


class LiveStateAudit(BaseModel):
    case_id: str
    deterministic_engine: dict[str, str]
    scenarios: list[TrajectoryScenario] = Field(default_factory=list)
    all_scenarios_deterministic: bool
    persona_guard_probes: list[PersonaGuardProbe] = Field(default_factory=list)
    persona_guard_passed: bool
    passed: bool
    notes: list[str] = Field(default_factory=list)


def build_live_state_audit(case: PreparedCase) -> LiveStateAudit:
    packet = build_trajectory_review_packet(case)
    probes = asyncio.run(_persona_guard_probes(case))
    all_scenarios_deterministic = all(scenario.deterministic for scenario in packet.scenarios)
    persona_guard_passed = all(probe.passed for probe in probes)
    notes = [
        "Trajectory scenarios are generated by backend.state.engine.EncounterEngine using the case TrajectorySpec.",
        "Persona probes use a mocked provider response that falsely says the patient is stable and gives wrong vitals; passing means the guard replaced that with code-held state.",
    ]
    if not _vitals_are_unstable(start_case(case).state.current_vitals):
        notes.append("Starting vitals did not meet the audit's unstable threshold; persona guard probes still ran, but clinician review should confirm scenario suitability.")
    return LiveStateAudit(
        case_id=case.case_id,
        deterministic_engine=packet.deterministic_engine,
        scenarios=packet.scenarios,
        all_scenarios_deterministic=all_scenarios_deterministic,
        persona_guard_probes=probes,
        persona_guard_passed=persona_guard_passed,
        passed=all_scenarios_deterministic and persona_guard_passed,
        notes=notes,
    )


async def _persona_guard_probes(case: PreparedCase) -> list[PersonaGuardProbe]:
    engine = start_case(case, session_id="live-state-audit")
    vitals = engine.state.current_vitals.model_copy(deep=True)
    model_claim, wrong_fragments = _wrong_stable_claim(vitals)

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200,
            json={
                "choices": [{"message": {"content": model_claim}}],
                "usage": {"prompt_tokens": 10, "completion_tokens": 14},
            },
        )

    client = LLMClient(
        LLMConfig(
            provider="openai_compatible",
            base_url="https://llm.example.test/v1/chat/completions",
            api_key="test-key",
        ),
        transport=httpx.MockTransport(handler),
    )

    role_contexts = {
        "patient": patient_context(case, engine.state, "Are you stable? What are the vitals?"),
        "nurse": nurse_context(case, engine.state),
        "consultant": consult_context(case, engine.state, "surgery"),
    }
    probes: list[PersonaGuardProbe] = []
    for role, context in role_contexts.items():
        result = await answer_persona(role, context, "Are they stable? What are the current vitals?", client)
        guarded = result.text
        stable_claim_removed = "stable" not in guarded.lower()
        wrong_vitals_removed = all(fragment not in guarded for fragment in wrong_fragments)
        state_anchor_present = _state_anchor_present(role, guarded, vitals)
        probes.append(
            PersonaGuardProbe(
                role=role,
                state_vitals=vitals,
                model_claim=model_claim,
                guarded_text=guarded,
                stable_claim_removed=stable_claim_removed,
                wrong_vitals_removed=wrong_vitals_removed,
                state_anchor_present=state_anchor_present,
                passed=stable_claim_removed and wrong_vitals_removed and state_anchor_present,
            )
        )
    return probes


def _wrong_stable_claim(vitals: VitalSigns) -> tuple[str, list[str]]:
    wrong_hr = _different_int(vitals.hr, 61)
    wrong_sbp = _different_int(vitals.sbp, 111)
    wrong_dbp = _different_int(vitals.dbp, 71)
    wrong_rr = _different_int(vitals.rr, 11)
    wrong_spo2 = _different_int(vitals.spo2, 88)
    wrong_pain = _different_int(vitals.pain if vitals.pain is not None else 10, 0)
    fragments = [
        f"HR {wrong_hr}",
        f"BP {wrong_sbp}/{wrong_dbp}",
        f"RR {wrong_rr}",
        f"SpO2 {wrong_spo2}%",
        f"Pain {wrong_pain}/10",
    ]
    return (
        "The patient is stable and comfortable. Current vitals: "
        + ", ".join(fragments)
        + ".",
        fragments,
    )


def _different_int(current: int | None, preferred: int) -> int:
    return preferred + 7 if current == preferred else preferred


def _state_anchor_present(role: str, text: str, vitals: VitalSigns) -> bool:
    if role == "patient":
        return "monitor numbers" in text.lower()
    required = [
        f"HR {vitals.hr}",
        f"BP {vitals.sbp}/{vitals.dbp}",
        f"RR {vitals.rr}",
        f"SpO2 {vitals.spo2}%",
    ]
    return all(fragment in text for fragment in required)


def _vitals_are_unstable(vitals: VitalSigns) -> bool:
    return any(
        [
            vitals.spo2 < 92,
            vitals.hr > 110,
            vitals.rr > 22,
            vitals.sbp < 90,
            vitals.pain is not None and vitals.pain >= 7,
        ]
    )


def _main() -> int:
    parser = argparse.ArgumentParser(description="Audit deterministic live-state behavior and persona state-consistency guards.")
    parser.add_argument("case", type=Path, help="PreparedCase JSON.")
    parser.add_argument("--output", type=Path, help="Optional live-state audit JSON output path.")
    args = parser.parse_args()

    case = PreparedCase.model_validate_json(args.case.read_text(encoding="utf-8"))
    audit = build_live_state_audit(case)
    rendered = audit.model_dump_json(indent=2)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered + "\n", encoding="utf-8")
    else:
        print(rendered)
    return 0 if audit.passed else 1


if __name__ == "__main__":
    raise SystemExit(_main())
